cloudflare workers model changes
payfunc/model-card pull request #101
Opened 2021-01-12 08:54 UTC by florianebmeier

## Change
Deprecate old Card and Card.Token and move to V1.
New Card does not have database identifier. 
New Card.Token has encrypted fields and no database identifiers.

## Rationale
To implement cloudflare workers, we do not want to save any data in databases and would prefer to have strong encrypted data in the token itself.

## Impact
Card is backwards compatible as it will still pass the typeguard and send less information. Card.Token only gained strongly encrypted information, so there will not be new information exposed.

## Risk
This should have no increased risks on the system. No extra risk analysis is necessary.

## Rollback
For rollback, it is enough to revert the commit and redeploy.

2021-01-12 11:57 UTC, simonmika requested changes

2021-01-12 11:57 UTC, simonmika commented on Card/Token.ts
> +		return baseUrl + ""
Can we get this in place?

2021-01-12 11:57 UTC, simonmika commented on Card/Token.ts
>  	export async function verify(token: authly.Token): Promise<(Token & authly.Payload) | undefined> {
I guess this requires updates, as we are mapping properties for this one?

2021-01-12 12:13 UTC, simonmika requested changes
Please address `verify` as well.

2021-01-12 12:13 UTC, simonmika commented on Card/Token.ts
> +		return baseUrl + "/card/" + token.encrypted + "." + token.expires[0] + "." + token.expires[1] + "/verification"
I suggest pad each to two zeros and concatenate without an extra dot.

2021-01-13 12:45 UTC, simonmika requested changes

2021-01-13 12:45 UTC, simonmika commented on Card/Token.ts
> +	encrypted: string
Can we have the "housekeeping" properties as well: `audience`, `created` etc?

2021-01-13 12:50 UTC, florianebmeier commented on Card/Token.ts
> +	encrypted: string
Should they be optional? otherwise we are gonna set them explicitly
it would be audience, created and issuer
Once they are signed and then verified they will be set but before that they will not be

2021-01-13 12:52 UTC, simonmika commented on Card/Token.ts
> +	encrypted: string
I think they should be mandatory. the only use case when not having them set is in the encryption and signing function itself. It can use `Partial<Token>`.

2021-01-13 14:19 UTC, simonmika approved these changes

2021-01-13 14:19 UTC, merged