Created Client
payfunc/model-card pull request #136
Opened 2021-08-17 07:25 UTC by nilssonemma

- [ ] Merge https://github.com/payfunc/model-base/pull/24 first

## Change
Added Client class for Card

## Rationale
Is used to create, update and get cards from frontend

## Impact
No impact

## Risk
This should have no increased risks on the system. No extra risk analysis is necessary.

## Rollback
For rollback, it is enough to revert the commit and redeploy.

2021-08-17 08:47 UTC, marcushanses submitted a review, later dismissed

2021-08-17 14:23 UTC, Magnus93 commented on Client/Card.ts
> +		return await this.client.connection.get<gracely.Error | gracely.Result>(`card/${card}`)
Technically writing `gracely.Error` as the Response type is redundant, since Connection.get/put/patch... returns `Response | gracely.Error`.

2021-08-17 14:51 UTC, robinnedergard commented on Client/index.ts
> +}
Can't we unite Client and Client.Card into one? We only need one client in this repository

2021-08-17 14:53 UTC, Magnus93 commented on Client/index.ts
> +	static open(url: string | undefined, token: string | undefined): Client | undefined {
You have the same input and outputs twice.
Remove extra overloding definition.

2021-08-17 15:05 UTC, robinnedergard requested changes

2021-08-17 15:05 UTC, robinnedergard commented on Client/Card.ts
> +}
Move functionality into Client (only one client in this repository)

2021-08-17 15:05 UTC, robinnedergard commented on Client/index.ts
> +	card = new ClientCard(this)
remove line (only one client in this repository)

2021-08-17 15:08 UTC, robinnedergard commented
Parity branch?

2021-08-17 15:14 UTC, Magnus93 requested changes

2021-08-17 15:14 UTC, Magnus93 commented on Client/index.ts
> +	card = new ClientCard(this)
@nilssonemma I think you created this client from the [model-acquirer client](https://github.com/payfunc/model-acquirer/blob/master/Client/index.ts) template which has an authorization-, merchant-, settlement- and verification-client. But since this only have one client you can make it in to a single client just like [client log](https://github.com/payfunc/model-log/pull/14/files)

2021-08-19 14:23 UTC, Magnus93 commented on Client/Card.ts
> +		return await this.client.connection.get<gracely.Error | gracely.Result>(`card/${card}`)
You can just write
```ts
async get(card: authly.Token): Promise<gracely.Error | gracely.Result> {
		return await this.client.connection.get<gracely.Result>(`card/${card}`)
}
```

2021-08-19 14:24 UTC, robinnedergard requested changes

2021-08-19 14:24 UTC, robinnedergard commented on Client/Card.ts
> +		return await this.client.connection.get<gracely.Error | gracely.Result>(`card/${card}`)
Return type should be `Promise<ModelCard, racely.Error>`

2021-08-19 14:31 UTC, robinnedergard commented on Client/Card.ts
> +		return await this.client.connection.get<gracely.Error | gracely.Result>(`card/${card}`)
No, mirror the type of `signed` in `gracely.success.created(signed)` or in general `result: T` in `gracely.success.ok(result)`

2021-08-19 14:44 UTC, robinnedergard requested changes

2021-08-19 14:44 UTC, robinnedergard commented on Client/Card.ts
> +	async get(card: authly.Token): Promise<gracely.Error | ModelCard> {
Hmm, not super important, but can we keep all the `gracely.Error` as the last return type for consistency? :)

2021-08-19 14:44 UTC, robinnedergard commented on package.json
> +  "@payfunc/model-base": "0.0.6",
Wrong version, should use non parity version `0.1.x`, also, make a parity branch where I assume this version `0.0.6` should be correct. :)

2021-08-19 14:47 UTC, robinnedergard commented on package.json
> +  "@payfunc/model-base": "0.0.6",
Also it's not a devDependency?

2021-08-23 07:45 UTC, Magnus93 submitted a review, later dismissed

2021-08-23 09:59 UTC, robinnedergard requested changes

2021-08-23 09:59 UTC, robinnedergard commented on package.json
> +  "@payfunc/model-base": "0.0.6",
I think we need to fix this so that we can import version 0.1.x of model-base, otherwise other errors might appear in workers that imports model-card through model-acquirer when model-acquirer gets updated.

2021-08-25 11:16 UTC, fredrikbryntesson approved these changes

2021-08-25 11:17 UTC, merged