Partial configuration
payfunc/model-card pull request #90
Opened 2020-11-16 14:53 UTC by robinnedergard

## Change

## Rationale

## Impact

## Risk
This should have no increased risks on the system. No extra risk analysis is necessary.

## Rollback
For rollback, it is enough to revert the commit and redeploy.

2020-11-17 15:04 UTC, simonmika requested changes

2020-11-17 15:04 UTC, simonmika commented on Merchant/UiKey.ts
> +export type UiKey = Omit<Key, "card"> & { card: Omit<Card, "acquirer" | "emv3d"> }
What does `UiKey` mean and why do we need it?

2020-11-17 15:35 UTC, robinnedergard commented on Merchant/UiKey.ts
> +export type UiKey = Omit<Key, "card"> & { card: Omit<Card, "acquirer" | "emv3d"> }
We use it in card-tokenizer

2020-11-17 16:22 UTC, simonmika commented on Merchant/UiKey.ts
> +export type UiKey = Omit<Key, "card"> & { card: Omit<Card, "acquirer" | "emv3d"> }
If you mean UI it is an abbreviation and up too the length of two letters we capitalize them both. However We should at least be able to use a better name. It has itself nothing to do with the UI. Maybe `Raw` would be the name?

But the question is why we can't use a Creatable in that context?

2020-11-18 09:14 UTC, robinnedergard commented on Merchant/UiKey.ts
> +export type UiKey = Omit<Key, "card"> & { card: Omit<Card, "acquirer" | "emv3d"> }
Replaced UiKey with function for extracting url, will be enough for card-tokeniser

2020-11-18 09:21 UTC, simonmika requested changes

2020-11-18 09:21 UTC, simonmika commented on Merchant/Key/index.spec.ts
> +		},
What type of keys are these? Please add comments with which type of secret they are signed.

2020-11-18 09:50 UTC, robinnedergard commented on Merchant/Key/index.spec.ts
> +		},
Added signing information for example keys.

2020-11-18 11:31 UTC, simonmika approved these changes

2020-11-18 15:18 UTC, merged